# Generated by Django 3.1.3 on 2021-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20211004_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bankid',
        ),
        migrations.AddField(
            model_name='customer',
            name='bankno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
